



#without  pasword

spring.application.name=IntroductionPage

# ============================
#   CLOUD DATABASE (KUNAL KA)
# ============================
spring.datasource.url=jdbc:mysql://mysql-7b0f85f-kunalukirde03.e.aivencloud.com:21216/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=

# ============================
#   JPA / HIBERNATE CONFIG
# ============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ============================
#   SERVER PORT
# ============================
server.port=8081
#
